# Use clang++ by default, but still allow `make CXX=g++`.
ifeq ($(origin CXX),default)
CXX := clang++
endif

# Tool and build defaults. `make` builds Vulkan unless BACKEND is overridden.
CLANG_FORMAT ?= clang-format
BACKEND ?= vulkan
UNAME_S := $(shell uname -s)

# All generated files live under build/.
BUILD_DIR := build
OBJ_DIR := $(BUILD_DIR)/obj
BIN_DIR := $(BUILD_DIR)/bin
LIB_DIR := $(BUILD_DIR)/lib

# Source roots.
ENGINE_DIR := engine
GAME_DIR := game

# EntryPoint.cpp contains `main()`. It is engine-owned code, but it must be
# linked into the final game executable, not into the dynamic engine library.
ENTRYPOINT_SOURCE := $(ENGINE_DIR)/EntryPoint.cpp

# Pick up new engine/game files automatically so the Makefile does not need to
# be edited every time a .cpp or .h file is added.
ENGINE_SOURCES := $(shell find $(ENGINE_DIR) -name '*.cpp' ! -name 'EntryPoint.cpp')
ALL_ENGINE_SOURCES := $(ENGINE_SOURCES) $(ENTRYPOINT_SOURCE)
ENGINE_HEADERS := $(shell find $(ENGINE_DIR) -name '*.h')
GAME_SOURCES := $(shell find $(GAME_DIR) -name '*.cpp')
GAME_HEADERS := $(shell find $(GAME_DIR) -name '*.h')
FORMAT_FILES := $(ENGINE_HEADERS) $(ALL_ENGINE_SOURCES) $(GAME_HEADERS) $(GAME_SOURCES)

# Object files mirror the source tree under build/obj/. Game objects are split
# by backend so Metal and Vulkan can use different compile flags later.
ENGINE_OBJECTS := $(ENGINE_SOURCES:%.cpp=$(OBJ_DIR)/engine-lib/%.o)
ENTRYPOINT_OBJECT := $(ENTRYPOINT_SOURCE:%.cpp=$(OBJ_DIR)/entrypoint/%.o)
METAL_GAME_OBJECTS := $(GAME_SOURCES:%.cpp=$(OBJ_DIR)/metal/%.o)
VULKAN_GAME_OBJECTS := $(GAME_SOURCES:%.cpp=$(OBJ_DIR)/vulkan/%.o)

# Dependency files are generated by `-MMD -MP`; they make header changes trigger
# the right recompiles.
DEPS := $(ENGINE_OBJECTS:.o=.d) $(ENTRYPOINT_OBJECT:.o=.d) $(METAL_GAME_OBJECTS:.o=.d) $(VULKAN_GAME_OBJECTS:.o=.d)

# Platform-specific dynamic library settings.
# macOS uses .dylib and @rpath; Linux uses .so and $ORIGIN.
ifeq ($(UNAME_S),Darwin)
SHARED_LIB_EXT := dylib
ENGINE_SONAME := libwalrus.$(SHARED_LIB_EXT)
ENGINE_SHARED_LDFLAGS := -dynamiclib -install_name @rpath/$(ENGINE_SONAME)
GAME_RPATH_LDFLAGS := -Wl,-rpath,@executable_path/../lib
PLATFORM_LDFLAGS :=
else
SHARED_LIB_EXT := so
ENGINE_SONAME := libwalrus.$(SHARED_LIB_EXT)
ENGINE_SHARED_LDFLAGS := -shared -Wl,-soname,$(ENGINE_SONAME)
GAME_RPATH_LDFLAGS := -Wl,-rpath,'$$ORIGIN/../lib'
PLATFORM_LDFLAGS := -lX11 -lX11-xcb -lxcb
endif

# Final output paths.
ENGINE_LIB := $(LIB_DIR)/$(ENGINE_SONAME)
METAL_BIN := $(BIN_DIR)/game-metal
VULKAN_BIN := $(BIN_DIR)/game-vulkan

# Common compiler flags.
CPPFLAGS += -I.
CXXFLAGS ?= -std=c++20 -Wall -Wextra -Wpedantic

# Hide symbols by default for dynamic library builds. Public engine APIs should
# be marked with WAPI, which expands to default visibility while building the
# engine.
VISIBILITY_FLAGS := -fvisibility=hidden -fvisibility-inlines-hidden
ENGINE_CPPFLAGS := $(CPPFLAGS) -DWALRUS_EXPORT
ENGINE_CXXFLAGS := $(CXXFLAGS) $(VISIBILITY_FLAGS) -fPIC
GAME_CXXFLAGS := $(CXXFLAGS) $(VISIBILITY_FLAGS)

# Link against build/lib/libwalrus.* and embed a runtime search path so game
# executables can find the engine library next to the build output.
ENGINE_LDFLAGS := -L$(LIB_DIR) -lwalrus $(GAME_RPATH_LDFLAGS)

# Backend-specific linker flags.
METAL_LDFLAGS := -framework Metal -framework MetalKit -framework QuartzCore -framework Cocoa

# Vulkan SDK paths come from the standard VULKAN_SDK environment variable.
ifdef VULKAN_SDK
VULKAN_CPPFLAGS := -I$(VULKAN_SDK)/include
VULKAN_LDFLAGS := -L$(VULKAN_SDK)/lib -Wl,-rpath,$(VULKAN_SDK)/lib -lvulkan
else
VULKAN_MISSING := 1
endif

# These targets are commands, not files to create.
.PHONY: all metal vulkan engine format clean

# Default target. Example overrides:
#   make BACKEND=metal
#   make BACKEND=vulkan
all:
	$(MAKE) $(BACKEND)

# Build only the engine dynamic library.
engine: format $(ENGINE_LIB)

# Build the game executable for the selected graphics backend.
metal: format $(METAL_BIN)

vulkan: format
ifeq ($(VULKAN_MISSING),1)
	$(error VULKAN_SDK is not set. Install the Vulkan SDK and run `make vulkan VULKAN_SDK=/path/to/VulkanSDK`)
endif
	$(MAKE) $(VULKAN_BIN)

# Keep source formatting automatic before builds.
format:
	$(CLANG_FORMAT) -i $(FORMAT_FILES)

# Link game executables. They include the backend-specific game objects,
# engine-owned entrypoint object, and dynamic engine library.
$(METAL_BIN): $(METAL_GAME_OBJECTS) $(ENTRYPOINT_OBJECT) $(ENGINE_LIB)
	@mkdir -p $(@D)
	$(CXX) $(GAME_CXXFLAGS) $(METAL_GAME_OBJECTS) $(ENTRYPOINT_OBJECT) $(ENGINE_LDFLAGS) -o $@ $(METAL_LDFLAGS)

$(VULKAN_BIN): $(VULKAN_GAME_OBJECTS) $(ENTRYPOINT_OBJECT) $(ENGINE_LIB)
	@mkdir -p $(@D)
	$(CXX) $(GAME_CXXFLAGS) $(VULKAN_GAME_OBJECTS) $(ENTRYPOINT_OBJECT) $(ENGINE_LDFLAGS) -o $@ $(VULKAN_LDFLAGS)

# Link the engine dynamic library from engine implementation objects.
$(ENGINE_LIB): $(ENGINE_OBJECTS)
	@mkdir -p $(@D)
	$(CXX) $(ENGINE_CXXFLAGS) $(ENGINE_SHARED_LDFLAGS) $(ENGINE_OBJECTS) -o $@ $(PLATFORM_LDFLAGS)

# Compile engine implementation files with WALRUS_EXPORT so WAPI marks public
# symbols for export from the dynamic library.
$(OBJ_DIR)/engine-lib/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(ENGINE_CPPFLAGS) $(ENGINE_CXXFLAGS) -MMD -MP -c $< -o $@

# Compile the engine-owned entrypoint as part of the game executable.
$(OBJ_DIR)/entrypoint/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(CPPFLAGS) $(GAME_CXXFLAGS) -MMD -MP -c $< -o $@

# Compile game files for each backend.
$(OBJ_DIR)/metal/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(CPPFLAGS) $(GAME_CXXFLAGS) -MMD -MP -c $< -o $@

$(OBJ_DIR)/vulkan/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(CPPFLAGS) $(VULKAN_CPPFLAGS) $(GAME_CXXFLAGS) -MMD -MP -c $< -o $@

clean:
	rm -rf $(BUILD_DIR)

# Include generated dependency files if they exist. The leading `-` avoids an
# error before the first build creates them.
-include $(DEPS)
